apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-only-forex
spec:
  podSelector: {}
  policyTypes: ["Ingress","Egress"]
  ingress:
  - from: [{podSelector: {}}]
  egress:
  - to: [{podSelector: {}}]
